name: Build and push

on: [ push ]

jobs:
  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          salsa: true
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    name: Matrix deploy
    needs: [ build ]
    strategy:
      matrix:
        cluster: [ dev-fss, dev-sbs, dev-gcp, prod-fss, prod-sbs, prod-gcp ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy to ${{ matrix.cluster }}
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml
          PRINT_PAYLOAD: true